In [1]:
import torch

In [ ]:
tensor = tor

In [3]:
head_size = 8
tensor = torch.randn(32, 4, 5)

batch_size, seq_len, dim = tensor.shape
tensor = tensor.reshape(batch_size // head_size, head_size, seq_len, dim)


In [4]:
tensor.shape

torch.Size([4, 8, 4, 5])

In [5]:
# 원래 batch를 잘라낸거였나?
tensor = tensor.permute(0, 2, 1, 3)

In [6]:
tensor.shape

torch.Size([4, 4, 8, 5])

In [7]:
tensor = tensor.reshape(batch_size//head_size, seq_len, head_size * dim)
tensor.shape

torch.Size([4, 4, 40])

In [9]:
tensor = torch.randn(32, 4, 5)

tensor = tensor.reshape(batch_size//head_size, seq_len, head_size * dim)

tensor.shape

torch.Size([4, 4, 40])

In [21]:
tensor = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],  # batch 1
    [[7, 8, 9], [10, 11, 12]],  # batch 2
    [[13, 14, 15], [16, 17, 18]],  # batch 3
    [[19, 20, 21], [22, 23, 24]]  # batch 4
])

In [13]:
tensor.shape

torch.Size([4, 2, 3])

In [14]:
batch_size, seq_len, dim = tensor.shape

In [16]:
head_size = 2

In [17]:
tensor = tensor.reshape(batch_size//head_size, seq_len, head_size * dim)

In [18]:
tensor.shape

torch.Size([2, 2, 6])

In [19]:
tensor

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]],

        [[13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [22]:
tensor = tensor.reshape(batch_size // head_size, head_size, seq_len, dim)
tensor

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])

In [23]:
tensor = tensor.permute(0, 2, 1, 3)
tensor


tensor([[[[ 1,  2,  3],
          [ 7,  8,  9]],

         [[ 4,  5,  6],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [19, 20, 21]],

         [[16, 17, 18],
          [22, 23, 24]]]])

In [24]:
tensor = tensor.reshape(batch_size // head_size, seq_len, dim * head_size)

tensor

tensor([[[ 1,  2,  3,  7,  8,  9],
         [ 4,  5,  6, 10, 11, 12]],

        [[13, 14, 15, 19, 20, 21],
         [16, 17, 18, 22, 23, 24]]])

In [1]:
t = 1.3
a = 1.9
a
type(a)

float

In [2]:
if t >= a:
    prinT('a')

In [1]:
import torcha


In [5]:
torch.randn(10, 3, 32, 32)[0].shape

torch.Size([3, 32, 32])

In [4]:
torch.randn(1, 3, 32, 32).repeat_interleave(3, dim=0).shape

torch.Size([3, 3, 32, 32])

In [5]:
class MyClass:
    def say_hello(self):
        print(f"Hello from {self}")

def shout():
    print("Shouting!")

# Create an instance of MyClass
my_instance = MyClass()

# Try to assign the function shout to the method say_hello
my_instance.say_hello = shout


In [6]:
my_instance.say_hello()

Shouting!


In [8]:
def shout(self):
    print(f"{self} is shouting!")

# Bind the function shout to my_instance as a method
my_instance.say_hello = shout.__get__(my_instance, MyClass)

# Now we can call say_hello, and it will execute the shout function
my_instance.say_hello()


<__main__.MyClass object at 0x7f3f7c7be080> is shouting!


In [7]:
class NameDescriptor:
    def __get__(self, instance, owner):
        if instance is None:
            return self
        print(f"Accessed name of {instance}")
        return instance._name

class Person:
    name = NameDescriptor()

    def __init__(self, name):
        self._name = name

p = Person("Alice")
print(p.name)  # This will print "Accessed name of <__main__.Person object at 0x7f8d8c3b3a90>" and "Alice"


Accessed name of <__main__.Person object at 0x7f3f7c7bcb80>
Alice


In [9]:
class Dog:
    def bark(self):
        print(f"{self.name} says woof!")

def meow():
    print("Meow!")

# Create an instance of Dog
my_dog = Dog()
my_dog.name = "Fido"

# Assign the function meow to the bark method
my_dog.bark = meow

# Now when we call bark, it will execute the meow function
my_dog.bark()  # This will print "Meow!"


Meow!


In [10]:
def purr(self):
    print(f"{self.name} says purr!")

# Bind the function purr to my_dog as a method
my_dog.bark = purr.__get__(my_dog, Dog)

# Now when we call bark, it will execute the purr function with access to my_dog
my_dog.bark()  # This will print "Fido says purr!"


Fido says purr!


In [1]:
import torch
import torch.nn.functional as F
from diffusers import UniPCMultistepScheduler
from diffusers.utils import load_image

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from diffusers.models.attention_processor import (
    AttnAddedKVProcessor,
    AttnAddedKVProcessor2_0,
    LoRAAttnAddedKVProcessor,
    LoRAAttnProcessor,
    LoRAAttnProcessor2_0,
    SlicedAttnAddedKVProcessor,
)

In [4]:
from diffusers.loaders import (
    LoraLoaderMixin,
    text_encoder_lora_state_dict,
)

In [5]:
from stable_diffusion_reference import StableDiffusionReferencePipeline

In [6]:
pipe = StableDiffusionReferencePipeline.from_pretrained(
       "runwayml/stable-diffusion-v1-5",
       safety_checker=None,
       torch_dtype=torch.float16,
       cache_dir='/workspace/hf_cache'
       ).to('cuda:0')

Loading pipeline components...: 100%|██████████| 6/6 [00:03<00:00,  1.63it/s]
You have disabled the safety checker for <class 'stable_diffusion_reference.StableDiffusionReferencePipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .


In [7]:
unet = pipe.unet

In [8]:
import gc

def prepare_unet(unet, model_type):
    assert model_type in ["sd_tiny", "sd_small"]
    # Set mid block to None if mode is other than base
    if model_type != "sd_small":
        unet.mid_block = None
        
    # Commence deletion of resnets/attentions inside the U-net
    # Handle Down Blocks
    for i in range(3):
        delattr(unet.down_blocks[i].resnets, "1")
        delattr(unet.down_blocks[i].attentions, "1")

    if model_type == "sd_tiny":
        delattr(unet.down_blocks, "3")
        unet.down_blocks[2].downsamplers = None

    else:
        delattr(unet.down_blocks[3].resnets, "1")
    # Handle Up blocks

    unet.up_blocks[0].resnets[1] = unet.up_blocks[0].resnets[2]
    delattr(unet.up_blocks[0].resnets, "2")
    for i in range(1, 4):
        unet.up_blocks[i].resnets[1] = unet.up_blocks[i].resnets[2]
        unet.up_blocks[i].attentions[1] = unet.up_blocks[i].attentions[2]
        delattr(unet.up_blocks[i].attentions, "2")
        delattr(unet.up_blocks[i].resnets, "2")
    if model_type == "sd_tiny":
        for i in range(3):
            unet.up_blocks[i] = unet.up_blocks[i + 1]
        delattr(unet.up_blocks, "3")
    torch.cuda.empty_cache()
    gc.collect()

In [9]:
prepare_unet(unet, "sd_small")

In [10]:
unet

UNet2DConditionModel(
  (conv_in): Conv2d(4, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (time_proj): Timesteps()
  (time_embedding): TimestepEmbedding(
    (linear_1): Linear(in_features=320, out_features=1280, bias=True)
    (act): SiLU()
    (linear_2): Linear(in_features=1280, out_features=1280, bias=True)
  )
  (down_blocks): ModuleList(
    (0): CrossAttnDownBlock2D(
      (attentions): ModuleList(
        (0): Transformer2DModel(
          (norm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (proj_in): LoRACompatibleConv(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (transformer_blocks): ModuleList(
            (0): BasicTransformerBlock(
              (norm1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
              (attn1): Attention(
                (to_q): Linear(in_features=320, out_features=320, bias=False)
                (to_k): Linear(in_features=320, out_features=320, bias=False)
                (to_v): Linear(in_features=320, 

In [ ]:
for name, attn_processor in unet.attn_processors.items():

In [4]:
pipe.unet

UNet2DConditionModel(
  (conv_in): Conv2d(4, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (time_proj): Timesteps()
  (time_embedding): TimestepEmbedding(
    (linear_1): Linear(in_features=320, out_features=1280, bias=True)
    (act): SiLU()
    (linear_2): Linear(in_features=1280, out_features=1280, bias=True)
  )
  (down_blocks): ModuleList(
    (0): CrossAttnDownBlock2D(
      (attentions): ModuleList(
        (0-1): 2 x Transformer2DModel(
          (norm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (proj_in): LoRACompatibleConv(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (transformer_blocks): ModuleList(
            (0): BasicTransformerBlock(
              (norm1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
              (attn1): Attention(
                (to_q): Linear(in_features=320, out_features=320, bias=False)
                (to_k): Linear(in_features=320, out_features=320, bias=False)
                (to_v): Linear(in_features

In [13]:
unet_lora_attn_procs = {}
unet_lora_parameters = []

for name, attn_processor in pipe.unet.attn_processors.items():
    cross_attention_dim = None if name.endswith("attn1.processor") else pipe.unet.config.cross_attention_dim
    if name.startswith("up_blocks"):
        block_id = int(name[len("up_blocks.")])
        hidden_size = list(reversed(pipe.unet.config.block_out_channels))[block_id]
        print(name, block_id, hidden_size)

    if isinstance(attn_processor, (AttnAddedKVProcessor, SlicedAttnAddedKVProcessor, AttnAddedKVProcessor2_0)):
            lora_attn_processor_class = LoRAAttnAddedKVProcessor
    else:
        lora_attn_processor_class = (
            LoRAAttnProcessor2_0 if hasattr(F, "scaled_dot_product_attention") else LoRAAttnProcessor
        )
    module = lora_attn_processor_class(
            hidden_size=hidden_size, cross_attention_dim=cross_attention_dim, rank=4
        )
    unet_lora_attn_procs[name] = module
    unet_lora_parameters.extend(module.parameters())

pipe.unet.set_attn_processor(unet_lora_attn_procs)

up_blocks.1.attentions.0.transformer_blocks.0.attn1.processor 1 1280
up_blocks.1.attentions.0.transformer_blocks.0.attn2.processor 1 1280
up_blocks.1.attentions.1.transformer_blocks.0.attn1.processor 1 1280
up_blocks.1.attentions.1.transformer_blocks.0.attn2.processor 1 1280
up_blocks.1.attentions.2.transformer_blocks.0.attn1.processor 1 1280
up_blocks.1.attentions.2.transformer_blocks.0.attn2.processor 1 1280
up_blocks.2.attentions.0.transformer_blocks.0.attn1.processor 2 640
up_blocks.2.attentions.0.transformer_blocks.0.attn2.processor 2 640
up_blocks.2.attentions.1.transformer_blocks.0.attn1.processor 2 640
up_blocks.2.attentions.1.transformer_blocks.0.attn2.processor 2 640
up_blocks.2.attentions.2.transformer_blocks.0.attn1.processor 2 640
up_blocks.2.attentions.2.transformer_blocks.0.attn2.processor 2 640
up_blocks.3.attentions.0.transformer_blocks.0.attn1.processor 3 320
up_blocks.3.attentions.0.transformer_blocks.0.attn2.processor 3 320
up_blocks.3.attentions.1.transformer_block

In [14]:
pipe.unet

UNet2DConditionModel(
  (conv_in): Conv2d(4, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (time_proj): Timesteps()
  (time_embedding): TimestepEmbedding(
    (linear_1): Linear(in_features=320, out_features=1280, bias=True)
    (act): SiLU()
    (linear_2): Linear(in_features=1280, out_features=1280, bias=True)
  )
  (down_blocks): ModuleList(
    (0): CrossAttnDownBlock2D(
      (attentions): ModuleList(
        (0-1): 2 x Transformer2DModel(
          (norm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (proj_in): LoRACompatibleConv(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (transformer_blocks): ModuleList(
            (0): BasicTransformerBlock(
              (norm1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
              (attn1): Attention(
                (to_q): Linear(in_features=320, out_features=320, bias=False)
                (to_k): Linear(in_features=320, out_features=320, bias=False)
                (to_v): Linear(in_features